---
settings:
  parallel: true

driver: vagrant
provisioner: 
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-graphite]
    - recipe[collectd::server]
    - recipe[ktc-collectd::client_graphite]
    - recipe[ktc-collectd::client_collectd]
    - recipe[ktc-gdash::default]
  attributes:
    gdash:
      monitor_client_recipe: "ktc-collectd\\:\\:client_collectd"
    ha_disabled: true
    etcd:
      args: -c 127.0.0.1:4001 -s 127.0.0.1:7001
      servers:
        - 127.0.0.1
