---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-graphite]
    - recipe[collectd::server]
    - recipe[ktc-collectd::client_graphite]
    - recipe[ktc-collectd::client_collectd]
    - recipe[ktc-gdash::default]
  attributes:
    gdash:
      monitor_client_recipe: "ktc-collectd\\:\\:client_collectd"
    ha_disabled: true
    etcd:
      args: -c 127.0.0.1:4001 -s 127.0.0.1:7001
      servers:
        - 127.0.0.1
